name: Build and Release JAR by Env Tag

on:
  push:
    tags:
      - '*-v*.*.*'  # uat-v1.0.0, cug-v1.2.3, prod-v2.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Environment from Tag
        id: extract_env
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          ENV_PREFIX="${TAG_NAME%%-*}"
          echo "env_prefix=$ENV_PREFIX" >> $GITHUB_OUTPUT

      - name: Set GitHub Environment
        id: set_env
        run: |
          PREFIX=${{ steps.extract_env.outputs.env_prefix }}
          ENV_NAME=$(echo $PREFIX | tr '[:lower:]' '[:upper:]')
          echo "env_name=$ENV_NAME" >> $GITHUB_OUTPUT

      - name: Setup Environment Context
        run: echo "Selected environment is ${{ steps.set_env.outputs.env_name }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ needs.build.outputs.env_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/*.jar
          retention-days: 3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}